# fly.toml app configuration file generated for kyztech-web-tool on 2023-06-16T16:34:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kyztech-web-tool"
primary_region = "nrt"

[env]
  PORT = "8888"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
